version: 2.1
orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@3.2.3
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm install --legacy-peer-deps
      - run:
          name: 'Run Tests'
          command: npm run test
      - run:
          name: 'Run Test Coverage'
          command: npm run test:cov
  upload-to-codecov:
    docker:
      - image: cimg/base:stable
    steps:
      - codecov/upload
workflows:
  build-and-test:
    jobs:
      - build-and-test
      - upload-to-codecov