version: 2.1
orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@3.2.3
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm install --legacy-peer-deps
      - run:
          name: 'Run Tests'
          command: npm run test
      - run:
          name: 'Run Test Coverage'
          command: npm run test:cov
      - codecov/upload:
          file: './coverage/clover.xml'
          token: 01b99bf6-6768-462f-9202-0c837eacbf2d  
workflows:
  build-and-test:
    jobs:
      - build-and-test