version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: "Run Tests"
          command: npm run test
      - run:
          name: "Run Test Coverage"
          command: npm run test:cov
workflows:
  build-and-test:
    jobs:
      - build-and-test